https://{default}/:
  type: upstream
  upstream: app:http
https://forum.platform.sh/:
  primary: null
  id: null
  attributes: {}
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  to: https://community.platform.sh
http://forum.platform.sh/:
  primary: null
  id: null
  attributes: {}
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  tls:
    strict_transport_security:
      enabled: null
      include_subdomains: null
      preload: null
    min_version: null
    client_authentication: null
    client_certificate_authorities: []
  to: https://community.platform.sh
